name: Pytests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          python -m pipenv install --dev --skip-lock
      - name: Run Flake8
        run: |
          python -m pipenv run flake8
      - name: Run Pytest
        run: |
          python -m pipenv run pytest